// <auto-generated />
using System;
using AbalfadhlTV.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbalfadhlTV.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220508200722_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Beqa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Child")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNeabati")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentBeqaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentBeqaId");

                    b.ToTable("Beqas");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.BeqaContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BeqaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeqaId");

                    b.ToTable("BeqaContacts");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.BeqaCoordinates", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BeqaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeqaId");

                    b.ToTable("BeqaCoordinates");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.BeqaTagType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BeqaTagTypes");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Camera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BeqaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsZerih")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZiaratOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeqaId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BeqaId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigestTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeqaId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.MediaFormat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FormatType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaFormats");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.PersonBeqa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BeqaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeathDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Father")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mather")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeqaId");

                    b.ToTable("PersonBeqas");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.CitiesImamzadeh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryImamzadehId")
                        .HasColumnType("bigint");

                    b.Property<string>("HashCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryImamzadehId");

                    b.ToTable("CitiesImamzadehs");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.CountryImamzadeh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("HashCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CountriesImamzadehs");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.ItemsImamzadeh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CitiesImamzadehId")
                        .HasColumnType("bigint");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("HashCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CitiesImamzadehId");

                    b.ToTable("ItemsImamzadehs");
                });

            modelBuilder.Entity("BeqaBeqaTagType", b =>
                {
                    b.Property<long>("BeqaTagTypesId")
                        .HasColumnType("bigint");

                    b.Property<long>("BeqasId")
                        .HasColumnType("bigint");

                    b.HasKey("BeqaTagTypesId", "BeqasId");

                    b.HasIndex("BeqasId");

                    b.ToTable("BeqaBeqaTagType");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Beqa", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", "ParentBeqa")
                        .WithMany("Beqas")
                        .HasForeignKey("ParentBeqaId");

                    b.Navigation("ParentBeqa");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.BeqaContact", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", "Beqa")
                        .WithMany("BeqaContacts")
                        .HasForeignKey("BeqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beqa");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.BeqaCoordinates", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", "Beqa")
                        .WithMany("BeqaCoordinatesCollection")
                        .HasForeignKey("BeqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beqa");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Camera", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", "Beqa")
                        .WithMany("Cameras")
                        .HasForeignKey("BeqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beqa");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Media", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", "Beqa")
                        .WithMany("Medias")
                        .HasForeignKey("BeqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beqa");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.MediaFormat", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Media", "Media")
                        .WithMany("MediaFormats")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.PersonBeqa", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", "Beqa")
                        .WithMany("PersonBeqas")
                        .HasForeignKey("BeqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beqa");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.CitiesImamzadeh", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.ImamzadehaAgg.CountryImamzadeh", "CountryImamzadeh")
                        .WithMany("CitiesImamzadeh")
                        .HasForeignKey("CountryImamzadehId");

                    b.Navigation("CountryImamzadeh");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.ItemsImamzadeh", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.ImamzadehaAgg.CitiesImamzadeh", "CitiesImamzadeh")
                        .WithMany("ItemsImamzadeh")
                        .HasForeignKey("CitiesImamzadehId");

                    b.Navigation("CitiesImamzadeh");
                });

            modelBuilder.Entity("BeqaBeqaTagType", b =>
                {
                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.BeqaTagType", null)
                        .WithMany()
                        .HasForeignKey("BeqaTagTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbalfadhlTV.Domain.BeqaAgg.Beqa", null)
                        .WithMany()
                        .HasForeignKey("BeqasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Beqa", b =>
                {
                    b.Navigation("BeqaContacts");

                    b.Navigation("BeqaCoordinatesCollection");

                    b.Navigation("Beqas");

                    b.Navigation("Cameras");

                    b.Navigation("Medias");

                    b.Navigation("PersonBeqas");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.BeqaAgg.Media", b =>
                {
                    b.Navigation("MediaFormats");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.CitiesImamzadeh", b =>
                {
                    b.Navigation("ItemsImamzadeh");
                });

            modelBuilder.Entity("AbalfadhlTV.Domain.ImamzadehaAgg.CountryImamzadeh", b =>
                {
                    b.Navigation("CitiesImamzadeh");
                });
#pragma warning restore 612, 618
        }
    }
}
