///////////////////////////////////////////////////////////
//  Film.cs
//  Implementation of the Class Film
//  Generated by Enterprise Architect
//  Created on:      09-«ıﬂ »—-2022 10:08:49 ».Ÿ
//  Original author: 0451256107
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">›Ì·„/ò·ÌÅ</span>
/// </p><p align="right" dir="rtl"></p>
/// </summary>
public class Film : Content {

	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ò·Ìœ «’·Ì</span></p>
	/// </summary>
	public int Id;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">‰Ê⁄/›—„   ’ÊÌ—</span>
	/// </p>
	/// </summary>
	public Enumerations.FilmFormatENUM FilmFormat;

	public Film(){

	}

	~Film(){

	}

}//end Film