///////////////////////////////////////////////////////////
//  FolderLog.cs
//  Implementation of the Class FolderLog
//  Generated by Enterprise Architect
//  Created on:      09-ÇõßÊÈÑ-2022 10:08:50 È.Ù
//  Original author: razi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">áÇ æÔå</span>
/// </p><p align="right" dir="rtl"></p>
/// </summary>
public class FolderLog {

	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">˜áíÏ ÇÕáí</span></p>
	/// </summary>
	public int Id;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÚäæÇä</span><span
	/// dir="ltr">/</span><span dir="rtl">ãæÖæÚ</span>
	/// </p><p dir="rtl"></p>
	/// </summary>
	public string Title;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÊæÖíÍÇÊ</span>
	/// </p><p dir="rtl"></p>
	/// </summary>
	public string Description;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">Âí˜ä</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public binary Icon;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÍĞİ ÔÏå</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public bool Deleted;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">˜Ï İåÑÓÊ</span><span
	/// dir="ltr">/</span><span dir="rtl">æÔå</span>
	/// </p><p align="right" dir="rtl">
	/// </p><p dir="rtl"></p>
	/// </summary>
	public int FolderCode;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">äæÚ ÏÓÊÑÓí İåÑÓÊ/æÔå</span>
	/// </p><p align="right" dir="rtl">
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public Enumerations.FolderAccessENUM FolderAccess;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">äæÚ ÂÑÔíæ</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public Enumerations.ArchiveTypeENUM ArchiveType;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">äæÚ ãÍÊæÇí æÔå</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public Enumerations.FolderContentTypeENUM FolderContentType;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÊÇÑíÎ æ ÒãÇä ÇíÌÇÏ</span></p>
	/// </summary>
	public DateTime CreationDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÊÇÑíÎ æ ÒãÇä ÇäŞÖÇÁ</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public DateTime ExpiretionDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÊÇÑíÎ æ ÒãÇä ÇäÊÔÇÑ</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public DateTime PublishDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÊÇÑíÎ æ ÒãÇä ÂÎÑíä ÊÛííÑ</span></p>
	/// </summary>
	public DateTime LastChangeDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÔäÇÓå ÂÎÑíä ˜ÇÑÈÑ ÊÛííÑ
	/// ÏåäÏå</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public int LastChangeUserId;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">æÖÚíÊ İáÏÑ</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public Enumerations.FolderStatusENUM FolderStatus;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÔãÇÑå ÊÑÊíÈ æÔå</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public int OrderID;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÔäÇÓå ÏÑ</span>
	/// </p><p align="right" dir="rtl"></p>
	/// </summary>
	public int ParentID;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ÊÇÑíÎ æ ÒãÇä áÇ</span></p>
	/// </summary>
	public DateTime LogDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">äæÚ ÊÑÇ˜äÔ</span></p>
	/// </summary>
	public Enumerations.TransactionTypeENUM TransactionType;
	public User m_User;

	public FolderLog(){

	}

	~FolderLog(){

	}

}//end FolderLog