///////////////////////////////////////////////////////////
//  Image.cs
//  Implementation of the Class Image
//  Generated by Enterprise Architect
//  Created on:      09-«ıﬂ »—-2022 10:08:48 ».Ÿ
//  Original author: 0451256107
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">⁄ò”/ ’ÊÌ—</span>
/// </p><p dir="rtl"></p>
/// </summary>
public class Image : Content {

	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ò·Ìœ «’·Ì</span></p>
	/// </summary>
	public int Id;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">‰Ê⁄/›—„   ’ÊÌ—</span></p>
	/// </summary>
	public Enumerations.ImageFormatENUM ImageFormat;

	public Image(){

	}

	~Image(){

	}

}//end Image