///////////////////////////////////////////////////////////
//  Sound.cs
//  Implementation of the Class Sound
//  Generated by Enterprise Architect
//  Created on:      09-«ıﬂ »—-2022 10:08:48 ».Ÿ
//  Original author: 0451256107
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">’Ê </span>
/// </p><p dir="rtl"></p>
/// </summary>
public class Sound : Content {

	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ò·Ìœ «’·Ì</span></p>
	/// </summary>
	public int Id;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">‰Ê⁄/›—„  ’Ê </span></p>
	/// </summary>
	public Enumerations.SoundFormatENUM SoundFormat;

	public Sound(){

	}

	~Sound(){

	}

}//end Sound