///////////////////////////////////////////////////////////
//  TextFile.cs
//  Implementation of the Class TextFile
//  Generated by Enterprise Architect
//  Created on:      09-«ıﬂ »—-2022 10:08:49 ».Ÿ
//  Original author: 0451256107
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">›«Ì· „ ‰Ì</span>
/// </p>
/// </summary>
public class TextFile : Content {

	/// <summary>
	/// <span dir="rtl">ò·Ìœ «’·Ì</span>
	/// </summary>
	public int Id;
	/// <summary>
	/// <span dir="rtl">‰Ê⁄/›—„  ›«Ì· „ ‰Ì</span>
	/// </summary>
	public Enumerations.TextFileFormatENUM TextFileFormat;

	public TextFile(){

	}

	~TextFile(){

	}

}//end TextFile