///////////////////////////////////////////////////////////
//  UserFolder.cs
//  Implementation of the Class UserFolder
//  Generated by Enterprise Architect
//  Created on:      09-«ıﬂ »—-2022 10:08:49 ».Ÿ
//  Original author: 0451256107
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">œ” —”Ì ò«—»— »Â
/// ›Â—” /¬·»Ê„/ÅÊ‘Â</span>
/// </p><p align="right" dir="rtl"></p>
/// </summary>
public class UserFolder {

	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ò·Ìœ «’·Ì</span></p>
	/// </summary>
	public int Id;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl"> «—ÌŒ «ÌÃ«œ œ” —”Ì</span></p>
	/// </summary>
	public DateTime CreationDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl"> «—ÌŒ «‰ﬁ÷«¡</span></p>
	/// </summary>
	public DateTime ExpirationDateTime;

	public UserFolder(){

	}

	~UserFolder(){

	}

}//end UserFolder