///////////////////////////////////////////////////////////
//  UserContentAction.cs
//  Implementation of the Class UserContentAction
//  Generated by Enterprise Architect
//  Created on:      09-«ıﬂ »—-2022 10:08:49 ».Ÿ
//  Original author: 0451256107
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// <p align="right" dir="rtl"><span dir="rtl">«ò‘‰ ò«—»— —ÊÌ „Õ Ê«</span></p>
/// </summary>
public class UserContentAction {

	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">ò·Ìœ «’·Ì</span></p>
	/// </summary>
	public int Id;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl">‰Ê⁄ «ò‘‰</span></p>
	/// </summary>
	public Enumerations.ActionTypeENUM ActionType;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl"> «—ÌŒ Ê “„«‰</span></p>
	/// </summary>
	public DateTime ActionDateTime;
	/// <summary>
	/// <p align="right" dir="rtl"><span dir="rtl"> Ê÷ÌÕ« </span>
	/// </p><p dir="rtl"></p>
	/// </summary>
	public string Description;

	public UserContentAction(){

	}

	~UserContentAction(){

	}

}//end UserContentAction